[
{ "py_library": {
    "name": "bootstrap",
    "py_sources": [ "bootstrap.py" ]
} },
{ "py_library": {
    "name": "spot",
    "py_sources": [ "spot.py" ]
} },
{ "py_library": {
    "name": "workqueue",
    "py_sources": [ "workqueue.py" ],
    "dependencies": [ ":bootstrap", ":spot" ]
} }
]